# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f674c4c95cef3459f43260323452a625286a18be172489ad384ad1fdb9d55b12e06ad87f078bbd18dfa0a6e6bdf2ac7481fd8249d8ddce6b23c26f8754242807

test:
  secret_key_base: 2af7ea2ec6b24b83097eeed89755df88126642de3bdc9b159fe2f1fb1ead956f457d5f603edaadb286196aa20ea35dc80a967fc9c3df8837539ca5e3e00b29a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
